language: go

os: osx

addons:
  chrome: stable

go:
  - "1.10"

before_script:
  - export DISPLAY=:0
  - java -jar sikulixsetup-1.1.3.jar options 1.1

script:
  - ls
  - sudo ./runsikulix -r ./sikulix/MultiTenantAPP.sikuli
