language: go

go:
  - "1.10"

script:
  - echo "success"
  - ls
  - export DISPLAY=:0.0
  - java -jar sikulixsetup-1.1.3.jar options x y z
  - sudo ~/sikulix/runsikulix -r ~/Desktop/SikulixRegressionScripts/MultiTenantAPP.sikuli
