language: go

go:
  - "1.10"

services:
  - xvfb

before_script:
  - xvfb-run java -jar sikulixsetup-1.1.3.jar options 1.1
script:
  - cat /home/travis/gopath/src/github.com/ChengyunYu/travis-sikuli-integration-test/SikuliX-1.1.3-SetupLog.txt
  - sudo ~/sikulix/runsikulix -r ~/Desktop/SikulixRegressionScripts/MultiTenantAPP.sikuli
