language: go

os: linux

go:
  - "1.10"

install:
  - sudo apt-get update
  - sudo apt-get install curl

script:
  - curl -X POST 9.112.232.82:8080/job/Sikulix%20UI/build --user admin:1122751ed9cd3cea8707ddbd0404c5e41f
  - curl -X 9.112.232.82:8080/job/Sikulix%20UI/lastBuild/consoleText --user admin:1122751ed9cd3cea8707ddbd0404c5e41f
