language: go

go:
  - "1.10"

services:
  - xvfb

before_install:
  - sudo apt-get update

install:
  - sudo apt-get update
  - sudo apt install libopencv-dev
  - sudo apt install tesseract-ocr

before_script:
  - export DISPLAY=:0
  - xvfb-run java -jar sikulixsetup-1.1.3.jar options 1.1

script:
  - ls
  - xvfb-run sudo ./runsikulix -r ./sikulix/MultiTenantAPP.sikuli
