language: go

os: osx

go:
  - "1.10"

install:
  - brew install google-chrome

before_script:
  - export DISPLAY=:0
  - java -jar sikulixsetup-1.1.3.jar options 1.1

script:
  - sudo ./runsikulix -r ./sikulix/MultiTenantAPP.sikuli
