language: go

go:
  - "1.10"

services:
  - xvfb

script:
  - echo $DISPLAY
  - export DISPLAY=:0.0
  - xvfb-run java -jar sikulixsetup-1.1.3.jar options x y z
  - sudo ~/sikulix/runsikulix -r ~/Desktop/SikulixRegressionScripts/MultiTenantAPP.sikuli
