language: go

go:
  - "1.10"

services:
  - xvfb

before_script:
  - xvfb-run java -jar sikulixsetup-1.1.3.jar options 2
script:
  - sudo ~/sikulix/runsikulix -r ~/Desktop/SikulixRegressionScripts/MultiTenantAPP.sikuli
