language: go

os: osx

addons:
  chrome: stable

go:
  - "1.10"

services:
  - xvfb

before_script:
  - export DISPLAY=:0
  - xvfb-run java -jar sikulixsetup-1.1.3.jar options 1.1

script:
  - ls
  - xvfb-run sudo ./runsikulix -r ./sikulix/MultiTenantAPP.sikuli
